# Generated by Django 2.2.1 on 2019-05-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKGROUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.CharField(max_length=100, unique=True, verbose_name='ID Группы')),
            ],
        ),
        migrations.CreateModel(
            name='VKGROUPREQUESTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_posts', models.IntegerField(max_length=100000)),
                ('date_time_request', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FilePathField(blank=True)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_create_request.VKGROUP')),
            ],
        ),
    ]
