# Generated by Django 2.2.1 on 2019-05-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_create_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vkgroup',
            options={'ordering': ['id_group'], 'verbose_name': 'Группа ВК', 'verbose_name_plural': 'Группы ВК'},
        ),
        migrations.AlterModelOptions(
            name='vkgrouprequests',
            options={'ordering': ['date_time_request'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запрос на парсинг'},
        ),
        migrations.AlterField(
            model_name='vkgrouprequests',
            name='count_posts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vkgrouprequests',
            name='id_group',
            field=models.CharField(max_length=100),
        ),
    ]
